In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix

In [2]:
PATH = "ml/predictions/preds_rf_290322.npy"
preds = np.load(PATH)

In [3]:
NUM_CHUNKS = 8
NUM_MODALITIES = 3
MOD_IND = 2
preds_0 = preds[::NUM_CHUNKS]
preds_wf = preds_0[MOD_IND::NUM_MODALITIES]

In [4]:
NUM_PYR = 83
NUM_PV = 21
labels = np.concatenate((np.ones(NUM_PYR), np.zeros(NUM_PV)))

In [5]:
def get_conf_mat(thr, labels, preds):
    preds_thr = preds_wf >= thr
    confs_thr = [confusion_matrix(labels, pred) for pred in preds_thr]
    conf_thr = np.median(confs_thr, axis=0)
    return conf_thr

The following confusion matrices were used for visualization

In [6]:
get_conf_mat(0.9, labels, preds_wf).round(3)

array([[21.,  0.],
       [15., 68.]])

In [7]:
get_conf_mat(0.1, labels, preds_wf).round(3)

array([[17.,  4.],
       [ 0., 83.]])

In [8]:
get_conf_mat(0.5, labels, preds_wf).round(3)

array([[20.,  1.],
       [ 1., 82.]])

In [9]:
get_conf_mat(0.45, labels, preds_wf).round(3)

array([[20.,  1.],
       [ 0., 83.]])