In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score

In [2]:
PATH = "ml/predictions/preds_rf_290322_rich.npy"
preds = np.load(PATH)

In [29]:
NUM_CHUNKS = 8
NUM_MODALITIES = 3
MOD_IND = 0
preds_0 = preds[1::NUM_CHUNKS]
preds_wf = preds_0[MOD_IND::NUM_MODALITIES]

In [30]:
NUM_PYR = 83
NUM_PV = 21
labels = np.concatenate((np.ones(NUM_PYR), np.zeros(NUM_PV)))

In [31]:
def get_conf_mat(thr, labels, preds):
    preds_thr = preds_wf >= thr
    confs_thr = [confusion_matrix(labels, pred) for pred in preds_thr]
    conf_thr = np.median(confs_thr, axis=0)
    return conf_thr

def get_auc(labels, preds):
    aucs = [roc_auc_score(labels, pred) for pred in preds]
    return np.median(aucs)

In [32]:
get_auc(labels, preds_wf)

0.9629948364888123

The following confusion matrices were used for visualization

In [33]:
get_conf_mat(0.9, labels, preds_wf).round(3)

array([[20.,  1.],
       [20., 63.]])

In [34]:
get_conf_mat(0.1, labels, preds_wf).round(3)

array([[ 6., 15.],
       [ 0., 83.]])

In [35]:
get_conf_mat(0.5, labels, preds_wf).round(3)

array([[15.,  6.],
       [ 2., 81.]])

In [38]:
get_conf_mat(0.72, labels, preds_wf).round(3)

array([[19.,  2.],
       [ 7., 76.]])

In [11]:
preds.shape

(1200, 104)